<?xml version="1.0"?>

<robot name="scout_mini_gazebo" xmlns:xacro="http://wiki.ros.org/xacro">
    <xacro:macro name="diff_drive_plugin">
        <gazebo>
            <plugin name="gazebo_ros_diff_drive" filename="libgazebo_ros_diff_drive.so">
                <ros>
                    <namespace>${robot_namespace}</namespace>
                    <remapping>odom:=zed_node/odom</remapping>
                </ros>
                <!-- Update rate in Hz -->
                <update_rate>30</update_rate>
                <!-- wheels -->
                <num_wheel_pairs>2</num_wheel_pairs>
                <left_joint>front_left_wheel</left_joint>
                <right_joint>front_right_wheel</right_joint>

                <left_joint>rear_left_wheel</left_joint>
                <right_joint>rear_right_wheel</right_joint>
                <!-- kinematics -->
                <wheel_separation>${track}</wheel_separation>
                <wheel_separation>${track}</wheel_separation>
                <wheel_diameter>${2*wheel_radius}</wheel_diameter>
                <wheel_diameter>${2*wheel_radius}</wheel_diameter>
                <!-- limits -->
                <max_wheel_torque>20</max_wheel_torque>
                <max_wheel_acceleration>1.0</max_wheel_acceleration>
                <!-- input -->
                <command_topic>cmd_vel</command_topic>
                <!-- output -->
                <publish_odom>true</publish_odom>
                <publish_odom_tf>false</publish_odom_tf>
                <publish_wheel_tf>true</publish_wheel_tf>
                <odometry_topic>zed_node/odom</odometry_topic>
                <odometry_frame>odom</odometry_frame>
                <robot_base_frame>base_footprint</robot_base_frame>
            </plugin>
        </gazebo>
    </xacro:macro>
</robot>